// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chatroom.Repositories.Models.EFCoreRepositories.ORM
{
    public partial class UsersWithRole
    {
        public Guid ID { get; set; }
        public Guid UserID { get; set; }
        public Guid RoleID { get; set; }
        public DateTimeOffset CreateDatetime { get; set; }
        public DateTimeOffset UpdatedDatetime { get; set; }

        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}